test_frontend:
    resource: "@TestFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

test_parser:
    resource: "@TestParserBundle/Controller/"
    type:     annotation
    prefix:   /

